version: '3.4'
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - dams-kafka-net
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_LOCAL://kafka:29092,LISTENER_REMOTE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_LOCAL://kafka:29092,LISTENER_REMOTE://ip-10-251-2-54.ap-south-1.compute.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_LOCAL:PLAINTEXT,LISTENER_REMOTE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_LOCAL
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: ./kafka/kafka-logs
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    depends_on:
      - "zookeeper"
    networks:
      - dams-kafka-net
networks:
  dams-kafka-net:
    name: dams-kafka-net